export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_ACTIVITIES = 'GET_ACTIVITIES';
export const SET_ORDER = 'SET_ORDER';
export const SET_FILTER_CONTINENT = 'SET_FILTER_CONTINENT';
export const SET_FILTER_ACTIVITY = 'SET_FILTER_ACTIVITY';
export const COMBINED_FILTERS = 'COMBINED_FILTERS';